### ISSUE TITLE
Caused by 0: java.lang.reflect.InvocationTargetException Crash

### ISSUE THREAD

**Issue by YukiRainee** [tr7zw/GraphUtil#3]
[crash-2022-12-19_20.35.59-fml.txt](https://github.com/tr7zw/GraphUtil/files/10265438/crash-2022-12-19_20.35.59-fml.txt)
Both Create Sifter and GraphUtil have this crash error hoping its not something else but hopefully this gets solved

**Comment by tr7zw** [comment]
Oof Forge, it could be that the build is for the original 1.19 Forge versions, possible that it never worked with 1.19(the later builds, thanks Forge)/1.19.1/1.19.2. 
You can thank Forge for that, guess I'll do a fixed 1.19.2 release.

**Comment by tr7zw** [comment]
Yea it's that issue, then doing all the fixes, the Forge version also is broken in that the always-on option doesn't work(Because of some stupid internal Forge changes?!?). Honestly, I won't fix the 1.19-1.19.2 versions, since apparently, no one noticed they don't work in the past 3 months. 
[graphutil-forge-1.0.0-mc1.19.2.zip](https://github.com/tr7zw/GraphUtil/files/10272474/graphutil-forge-1.0.0-mc1.19.2.zip)
Here is a version that starts, but as I said, the always-on option won't work. The 1.19.3 version is fine.
